server.port : 8888
spring:
  cloud:
    config:
      server:
        git:
          uri : https://github.com/ashokprajapati999/Config-repo/
          username: ashokprajapati999@gmail.com
          password: Java@1234
          force-pull: true

spring.security.user.name: ashokprajapati999@gmail.com
spring.security.user.password: Java@1234

