server.port : 8888
spring:
  cloud:
    config:
      server:
        git:
          uri : https://github.com/ashokprajapati999/Config-repo/
          username: ${git_user}
          password: ${git_password}
          force-pull: true

spring.security.user.name: config_user
spring.security.user.password: Lwre15qlw@

